#!/bin/bash

# Upload HF Usage Examples
# This script monitors checkpoint directories and uploads last.pth to HuggingFace

echo "=== Upload HF Monitor - Usage Examples ==="
echo ""
echo "1. Basic usage (check every 60 seconds):"
echo "   python upload_hf.py --input_path /path/to/your/outputs"
echo ""
echo "2. Custom check interval (5 minutes):"
echo "   python upload_hf.py --input_path /path/to/your/outputs --interval 300"
echo ""
echo "3. Custom HuggingFace username:"
echo "   python upload_hf.py --input_path /path/to/your/outputs --hf_user your-username"
echo ""
echo "4. Run in background with nohup:"
echo "   nohup python upload_hf.py --input_path /path/to/your/outputs > upload.log 2>&1 &"
echo ""
echo "Expected directory structure:"
echo "   input_path/"
echo "   └── */"
echo "       └── */"
echo "           └── */"
echo "               └── ckpt/"
echo "                   ├── epoch1-xxxxx"
echo "                   ├── epoch2-xxxxx"
echo "                   ├── epoch10-xxxxx"
echo "                   └── last.pth"
echo ""
echo "The script will:"
echo "- Monitor for new epoch files (epoch{x}-*)"
echo "- Upload only last.pth when a new epoch is detected"
echo "- Create timestamped repositories (repo-name-YYYYMMDD_HHMMSS)"
echo "- Keep only the latest 3 repositories"
echo ""
echo "Environment variables:"
echo "   export HF_TOKEN=your_huggingface_token"
